### ISSUE TITLE
It's Sunday night, so let's change the background colours of the gradient for the week of Feb 5th to Feb 11th

### ISSUE THREAD

**Issue by DarrenfJ** [RomchyFCC/GitHub-Practice-For-All#14]
Sunday night requesting a change to the background colors of the page.

If you look at the CSS [here](https://github.com/RomchyFCC/GitHub-Practice-For-All/blob/master/The%20Website/style.css) you can see:

``` CSS
body {
	margin: 0;
	padding: 0;
	background: linear-gradient(90deg, purple, blue);
}
```

Let's change the `background: linear-gradient(90deg, purple, blue);`to something new.

You decide the [angle](https://developer.mozilla.org/en-US/docs/Web/CSS/linear-gradient) and [colors](https://developer.mozilla.org/en-US/docs/Web/CSS/color_value)
