### ISSUE TITLE
Switching name positions randomly on the page

### ISSUE THREAD

**Issue by RomchyFCC** [RomchyFCC/GitHub-Practice-For-All#18]
1. pick a random name
2. find the selector it has(if it doesn't have one, you should add it)
3. give it a position of absolute
4. give it a random number of top and left
5. repeat 2 times

example CSS would be:
``` CSS
#romchy {
	position: absolute;
	top: 350px;
	left: 900px;
}
```
